# Generated by Django 5.2.9 on 2026-04-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0066_remove_blog_analytics_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='medium', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='截止日期')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成日期')),
                ('is_recurring', models.BooleanField(db_index=True, default=False, verbose_name='是否周期性任务')),
                ('recurring_type', models.CharField(blank=True, choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('yearly', '每年'), ('custom', '自定义')], max_length=20, null=True, verbose_name='周期类型')),
                ('recurring_interval', models.IntegerField(default=1, verbose_name='周期间隔（天/周/月/年）')),
                ('next_occurrence', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='下次出现时间')),
                ('tags', models.TextField(blank=True, default='[]', verbose_name='标签')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='blogs.blog')),
            ],
            options={
                'ordering': ['-order', '-created_date'],
                'indexes': [models.Index(fields=['blog', 'status'], name='todo_blog_status'), models.Index(fields=['blog', 'due_date'], name='todo_blog_due_date'), models.Index(fields=['blog', 'is_recurring'], name='todo_blog_recurring')],
            },
        ),
    ]
