# Generated by Django 5.2.9 on 2026-04-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0067_add_todo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(max_length=500, verbose_name='链接')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述/备注')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='公开可见')),
                ('tags', models.TextField(blank=True, default='[]', verbose_name='标签')),
                ('clicks', models.IntegerField(db_index=True, default=0, verbose_name='点击次数')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blogs.blog')),
            ],
            options={
                'ordering': ['-order', '-created_date'],
                'indexes': [models.Index(fields=['blog', 'is_public'], name='bookmark_blog_public'), models.Index(fields=['is_public', 'created_date'], name='bookmark_public_date')],
            },
        ),
    ]
